memory_limit = 256M
upload_max_filesize = 11M
; > upload_max_filesize: il body multipart include anche i campi del form
post_max_size = 13M
max_execution_time = 30
date.timezone = UTC
expose_php = Off
